In [8]:
import numpy as np

M=np.random.random((4,4))
print(M)
print(M.sum())
print(" ==== min ====")
print(M.min(axis=0))
print(M.min(axis=1))
print(" ==== max ====")
print(M.max(axis=0))
print(M.max(axis=1))
print(" ==== sum ====")
print(M.sum(axis=0))
print(M.sum(axis=1))


[[0.67432404 0.90712961 0.44047645 0.32877987]
 [0.22445696 0.7424593  0.30067196 0.68027863]
 [0.82869901 0.30264764 0.73512967 0.45221243]
 [0.65522602 0.19209983 0.62297477 0.96143096]]
9.048997139605962
 ==== min ====
[0.22445696 0.19209983 0.30067196 0.32877987]
[0.32877987 0.22445696 0.30264764 0.19209983]
 ==== max ====
[0.82869901 0.90712961 0.73512967 0.96143096]
[0.90712961 0.7424593  0.82869901 0.96143096]
 ==== sum ====
[2.38270603 2.14433638 2.09925285 2.42270188]
[2.35070996 1.94786685 2.31868875 2.43173158]
