In [36]:
scores=[83, 98, 56]
for i in range(len(scores)):
    print(scores[i])

83
98
56


In [37]:
list1 = ["香蕉", "蘋果", "橘子"]
n = list1.count("蘋果")
m = list1.count("西瓜")

In [38]:
list1 = [1, 2, 3, 4, 5, 6]
list1.insert(3, "豬頭")
print(list1)

[1, 2, 3, '豬頭', 4, 5, 6]


In [39]:
list1 = [1, 2, 3, 4, 5, 6]
list1.insert(-1, "鳳梨蝦球")
print(list1)
list1.insert(12, "高麗菜")
print(list1)

[1, 2, 3, 4, 5, '鳳梨蝦球', 6]
[1, 2, 3, 4, 5, '鳳梨蝦球', 6, '高麗菜']


In [40]:
list1 =["春天", "夏天", "秋天", "冬天"]
list1.remove("夏天")
print(list1)

['春天', '秋天', '冬天']


In [41]:
list1 = [1, 2, 3, 4, 5, 6]
n = list1.pop()
print(list1, n)
n = list1.pop(2)
print(list1, n)

[1, 2, 3, 4, 5] 6
[1, 2, 4, 5] 3


In [42]:
list1 = [1, 2, 3, 4, 5, 6]
del list1[1]
print(list1)
list2 = [1, 2, 3, 4, 5, 6]
del list2[1:5:2]
print(list2)

[1, 3, 4, 5, 6]
[1, 3, 5, 6]


In [43]:
list1 = [3, 2, 1, 5]
list1.sort()
print(list1)

[1, 2, 3, 5]


In [44]:
list1 = [3, 2, 1, 5]
list2=sorted(list1, reverse=True)
print(list2)
print(list1)

[5, 3, 2, 1]
[3, 2, 1, 5]


In [45]:
tuple1 = (1, 2, 3, 4, 5)
tuple2 = (1, "紅豆", True)


In [46]:
tuple3 = ("綠豆", "紅豆", "花生")
tuple3[1]="黃豆"


TypeError: 'tuple' object does not support item assignment

In [ ]:
tuple1=(1,2,3,4,5)
list1=list(tuple1)
list1.append(8)

In [ ]:
list2=[1,2,3,4,5]
tuple2=tuple(list2)
tuple2.append(8)

In [ ]:
dict2={"香蕉":20, "蘋果":50, "橘子":30, "香蕉":25}
print(dict2)

In [60]:
dict1={"香蕉":20, "蘋果":50, "橘子":30}
print(dict1)

{'香蕉': 20, '蘋果': 50, '橘子': 30}


In [10]:
dict1={"joe":5, "mary":8}
value1=dict1.values()
print(value1, type(value1))


dict_values([5, 8]) <class 'dict_values'>


In [3]:
dict1={"香蕉":20, "蘋果":50, "橘子":30}
key1 = list(dict1.keys())
print(key1[0])

香蕉


In [2]:
float("56")

56.0

In [5]:
def sum(a, b):
    return a + b

def debug(func):
    print('接到 func', func.__name__)
    def wrapper(*args, **kwargs):
        print('幫忙代入 args', args)
        print('幫忙代入 kwargs', kwargs)
        func(*args, **kwargs)
    return wrapper

debug_sum = debug(sum)
debug_sum(1, 2)
print('debug_sum', debug_sum)

接到 func sum
幫忙代入 args (1, 2)
幫忙代入 kwargs {}
debug_sum <function debug.<locals>.wrapper at 0x000001B58AD9A160>


In [1]:
import numpy as np

a=np.array([1,2,3,4])
b=np.array((1,2,3,4))
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [2]:
c=np.arange(3,30,3)
print(c)


[ 3  6  9 12 15 18 21 24 27]


In [3]:
d=np.linspace(0,10,5)
print(d)


[ 0.   2.5  5.   7.5 10. ]


In [4]:
c=np.arange(3,30,3)
print(c)
print(c[0])  # 取得在index位置0的元素
print(c[1])  # 取得在index位置1的元素
print(c[2:6])  # 取得在index位置2-5(包含2但不含6)的子陣列(subarray)
print(c[1:-1:2])  # 取得陣列c中index位置1,3,5,..(各間隔1個元素來選取)的子陣列


[ 3  6  9 12 15 18 21 24 27]
3
6
[ 9 12 15 18]
[ 6 12 18 24]


In [5]:
two_dim=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
three_dim=np.array([[[1,2,3,4],
                     [5,6,7,8],
                     [9,10,11,12]],
                    [[13,14,15,16],
                     [17,18,19,20],
                     [21,22,23,24]]])
print(two_dim.shape)
print(three_dim.shape)


(3, 4)
(2, 3, 4)
